Update default_payload configuration to use custom_params instead
StackStorm-Exchange/stackstorm-servicenow pull request #7
Opened 2018-02-11 13:40 UTC by jamie-owen

I had some time to review this and I broke some existing functionality in my last patch. Although passing `default_params` to the client during initialisation had been deprecated it's still possible to add custom parameters to the client through methods detailed [here](http://pysnow.readthedocs.io/en/stable/usage/parameters.html).

2018-02-11 22:13 UTC, bigmstone requested changes
Thanks for fixing this up. I think the API change makes sense here - especially since the existing config option isn't used anywhere. Have a couple of requests to improve the PR a bit and we can get it merged.

2018-02-11 22:13 UTC, bigmstone commented on actions/lib/actions.py
> +        s = sn.Client(instance=instance_name, user=username, password=password)
I believe a more explicit name would be better here. Perhaps `client` or something similar.

2018-02-11 22:13 UTC, bigmstone commented on actions/lib/actions.py
> +        if 'custom_params' in self.config:
Let's also assert `custom_params` is type `dict` before passing it to Service Now. Will make this piece a tad more robust.

2018-02-12 11:30 UTC, jamie-owen commented
Thanks for reviewing, changes pushed.

The following definition in `config.schema.yaml` enforces the type from the Stackstorm perspective. E.g. An exception is thrown if a user tries to register bad config.

```
custom_params:
  description: "ServiceNow options that will be passed to all requests"
  type: object
  required: false
```

With that in mind, can you think of a reason why the explicit type check is still worth doing in `actions.py`?

2018-02-12 20:38 UTC, bigmstone approved these changes

2018-02-12 20:38 UTC, bigmstone commented
That should be enough. I just personally like to check as close to the usage as possible. That said looks good to merge. Thanks again.

2018-02-12 20:39 UTC, merged